### ISSUE TITLE
"Not a valid URI" message when pasting a new URI into resource template

### ISSUE THREAD

**Issue by timathom** [LD4P/sinopia_editor#2059]
* I have simple a “resource”-type template (i.e., no nested valueTemplateRefs) defined for item-level genre/form terms in this template: https://stage.sinopia.io/editor/Yale:RT:BF2:Monograph:Item-CtY-BR. We want to be able to paste in arbitrary URIs. It seems to work, but Sinopia displays an error message stating, “Not a valid URI,” even though the URI is valid. This is a usability issue that confuses catalogers.

* Also, the URI is not turned into a link (not dereferenceable from the Sinopia UI).

* For "lookup"-type templates, pasting a new URI into the field does not generate the error message, but the URI is still not turned into a link. Also, the URI is serialized as a string literal rather than a resource (see issue #2060).

<img width="518" alt="Screenshot 2020-01-26 13 02 23" src="https://user-images.githubusercontent.com/5334524/73139519-cd9c2800-403c-11ea-8190-76e077cf79dc.png">

**Comment by michelleif** [comment]
What is the hoped for output from this field?
Is it:
<Item> <http://id.loc.gov/ontologies/bibframe/genreForm> <URI for genre, entered by cataloger>
Why do you have this defined as a type = resource?
Why not a look up to rbms vocabs? because those aren't set up in QA yet?

in any case you are right, it shouldn't give that "Not a valid URI" message. @jermnelson what is this kind of field expecting as a valid URI? (I couldn't tell from experimenting). Is it expecting a www?

**Comment by jermnelson** [comment]
Confirmed issue; the problem is with changing focus from the field after inputting and hitting enter a valid URL into the URL field.

**Comment by timathom** [comment]
@michelleif Yes, the RBMS vocabs are not yet set up in QA to my knowledge. That's why it is `type = resource`. I don't want to make it a lookup template (e.g., to LC Genre/Form) because then pasting in a URI generates unwanted results when QA tries to resolve it as a string.

**Comment by michelleif** [comment]
#2060 is fixed (entered URI not getting serialized properly)

**Comment by michelleif** [comment]
also the URI is now getting properly turned into a link, so what remains is the title of this ticket, to fix the erroneous error message

**Comment by michelleif** [comment]
this seems fixed. @timathom can you confirm (either stage or PRD) that you can now paste a URI without an error?

**Comment by timathom** [comment]
@michelleif Yes, I can now paste without an error, and the URI is correctly serialized as a resource URI. However, it is still not made into an actionable link.

**Comment by michelleif** [comment]
thanks for testing @timathom , I'm going to create a new ticket for the actionable link part, and close this one since the error message problem is fixed.
